//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imperial
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTipoNave
    {
        public tTipoNave()
        {
            this.tNave = new HashSet<tNave>();
        }
    
        public int Codigo { get; set; }
        public string Denominacion { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<int> NumTripulantes { get; set; }
    
        public virtual ICollection<tNave> tNave { get; set; }

        public override string ToString()
        {
            return Denominacion;
        }
    }
}
