//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace control2_2122_EnitytFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class control2_2122Entities : DbContext
    {
        public control2_2122Entities()
            : base("name=control2_2122Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tPaciente> tPaciente { get; set; }
        public virtual DbSet<tProvincia> tProvincia { get; set; }
        public virtual DbSet<tPruebas> tPruebas { get; set; }
        public virtual DbSet<tReferenciasGlucosa> tReferenciasGlucosa { get; set; }
    }
}
