//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace control2_2122_EnitytFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPruebas
    {
        public int ID { get; set; }
        public string NIF { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public Nullable<float> valor_glucosa { get; set; }
    
        public virtual tPaciente tPaciente { get; set; }
    }
}
