//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace control2_2122_EnitytFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReferenciasGlucosa
    {
        public int ID { get; set; }
        public float desde { get; set; }
        public float hasta { get; set; }
        public string categoria { get; set; }
    }
}
