#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace control2_2122_LINQ2SQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="control2_2122")]
	public partial class BDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttPaciente(tPaciente instance);
    partial void UpdatetPaciente(tPaciente instance);
    partial void DeletetPaciente(tPaciente instance);
    partial void InserttReferenciasGlucosa(tReferenciasGlucosa instance);
    partial void UpdatetReferenciasGlucosa(tReferenciasGlucosa instance);
    partial void DeletetReferenciasGlucosa(tReferenciasGlucosa instance);
    partial void InserttProvincia(tProvincia instance);
    partial void UpdatetProvincia(tProvincia instance);
    partial void DeletetProvincia(tProvincia instance);
    partial void InserttPruebas(tPruebas instance);
    partial void UpdatetPruebas(tPruebas instance);
    partial void DeletetPruebas(tPruebas instance);
    #endregion
		
		public BDDataContext() : 
				base(global::control2_2122_LINQ2SQL.Properties.Settings.Default.control2_2122ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tPaciente> tPaciente
		{
			get
			{
				return this.GetTable<tPaciente>();
			}
		}
		
		public System.Data.Linq.Table<tReferenciasGlucosa> tReferenciasGlucosa
		{
			get
			{
				return this.GetTable<tReferenciasGlucosa>();
			}
		}
		
		public System.Data.Linq.Table<tProvincia> tProvincia
		{
			get
			{
				return this.GetTable<tProvincia>();
			}
		}
		
		public System.Data.Linq.Table<tPruebas> tPruebas
		{
			get
			{
				return this.GetTable<tPruebas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tPaciente")]
	public partial class tPaciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NIF;
		
		private int _NumSeguro;
		
		private string _Nombre;
		
		private string _Apellidos;
		
		private string _Sexo;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Direccion;
		
		private string _Poblacion;
		
		private string _Provincia;
		
		private string _CodigoPostal;
		
		private string _Telefono;
		
		private string _e_mail;
		
		private EntitySet<tPruebas> _tPruebas;
		
		private EntityRef<tProvincia> _tProvincia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNIFChanging(string value);
    partial void OnNIFChanged();
    partial void OnNumSeguroChanging(int value);
    partial void OnNumSeguroChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnFechaNacimientoChanging(System.DateTime value);
    partial void OnFechaNacimientoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnPoblacionChanging(string value);
    partial void OnPoblacionChanged();
    partial void OnProvinciaChanging(string value);
    partial void OnProvinciaChanged();
    partial void OnCodigoPostalChanging(string value);
    partial void OnCodigoPostalChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void One_mailChanging(string value);
    partial void One_mailChanged();
        #endregion

        public override string ToString()
        {
            return NIF + ";" + Nombre + ";" + Apellidos;
        }
        public tPaciente()
		{
			this._tPruebas = new EntitySet<tPruebas>(new Action<tPruebas>(this.attach_tPruebas), new Action<tPruebas>(this.detach_tPruebas));
			this._tProvincia = default(EntityRef<tProvincia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIF", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NIF
		{
			get
			{
				return this._NIF;
			}
			set
			{
				if ((this._NIF != value))
				{
					this.OnNIFChanging(value);
					this.SendPropertyChanging();
					this._NIF = value;
					this.SendPropertyChanged("NIF");
					this.OnNIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumSeguro", DbType="Int NOT NULL")]
		public int NumSeguro
		{
			get
			{
				return this._NumSeguro;
			}
			set
			{
				if ((this._NumSeguro != value))
				{
					this.OnNumSeguroChanging(value);
					this.SendPropertyChanging();
					this._NumSeguro = value;
					this.SendPropertyChanged("NumSeguro");
					this.OnNumSeguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(80)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poblacion", DbType="VarChar(50)")]
		public string Poblacion
		{
			get
			{
				return this._Poblacion;
			}
			set
			{
				if ((this._Poblacion != value))
				{
					this.OnPoblacionChanging(value);
					this.SendPropertyChanging();
					this._Poblacion = value;
					this.SendPropertyChanged("Poblacion");
					this.OnPoblacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					if (this._tProvincia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProvinciaChanging(value);
					this.SendPropertyChanging();
					this._Provincia = value;
					this.SendPropertyChanged("Provincia");
					this.OnProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostal", DbType="VarChar(50)")]
		public string CodigoPostal
		{
			get
			{
				return this._CodigoPostal;
			}
			set
			{
				if ((this._CodigoPostal != value))
				{
					this.OnCodigoPostalChanging(value);
					this.SendPropertyChanging();
					this._CodigoPostal = value;
					this.SendPropertyChanged("CodigoPostal");
					this.OnCodigoPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_mail", DbType="VarChar(50)")]
		public string e_mail
		{
			get
			{
				return this._e_mail;
			}
			set
			{
				if ((this._e_mail != value))
				{
					this.One_mailChanging(value);
					this.SendPropertyChanging();
					this._e_mail = value;
					this.SendPropertyChanged("e_mail");
					this.One_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tPaciente_tPruebas", Storage="_tPruebas", ThisKey="NIF", OtherKey="NIF")]
		public EntitySet<tPruebas> tPruebas
		{
			get
			{
				return this._tPruebas;
			}
			set
			{
				this._tPruebas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tProvincia_tPaciente", Storage="_tProvincia", ThisKey="Provincia", OtherKey="Codigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tProvincia tProvincia
		{
			get
			{
				return this._tProvincia.Entity;
			}
			set
			{
				tProvincia previousValue = this._tProvincia.Entity;
				if (((previousValue != value) 
							|| (this._tProvincia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tProvincia.Entity = null;
						previousValue.tPaciente.Remove(this);
					}
					this._tProvincia.Entity = value;
					if ((value != null))
					{
						value.tPaciente.Add(this);
						this._Provincia = value.Codigo;
					}
					else
					{
						this._Provincia = default(string);
					}
					this.SendPropertyChanged("tProvincia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tPruebas(tPruebas entity)
		{
			this.SendPropertyChanging();
			entity.tPaciente = this;
		}
		
		private void detach_tPruebas(tPruebas entity)
		{
			this.SendPropertyChanging();
			entity.tPaciente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tReferenciasGlucosa")]
	public partial class tReferenciasGlucosa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private float _desde;
		
		private float _hasta;
		
		private string _categoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OndesdeChanging(float value);
    partial void OndesdeChanged();
    partial void OnhastaChanging(float value);
    partial void OnhastaChanged();
    partial void OncategoriaChanging(string value);
    partial void OncategoriaChanged();
    #endregion
		
		public tReferenciasGlucosa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desde", DbType="Real NOT NULL")]
		public float desde
		{
			get
			{
				return this._desde;
			}
			set
			{
				if ((this._desde != value))
				{
					this.OndesdeChanging(value);
					this.SendPropertyChanging();
					this._desde = value;
					this.SendPropertyChanged("desde");
					this.OndesdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasta", DbType="Real NOT NULL")]
		public float hasta
		{
			get
			{
				return this._hasta;
			}
			set
			{
				if ((this._hasta != value))
				{
					this.OnhastaChanging(value);
					this.SendPropertyChanging();
					this._hasta = value;
					this.SendPropertyChanged("hasta");
					this.OnhastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this.OncategoriaChanging(value);
					this.SendPropertyChanging();
					this._categoria = value;
					this.SendPropertyChanged("categoria");
					this.OncategoriaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tProvincia")]
	public partial class tProvincia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Codigo;
		
		private string _Nombre;
		
		private EntitySet<tPaciente> _tPaciente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
		#endregion
		public override string ToString()
		{
			return Nombre;
		}
		public tProvincia()
		{
			this._tPaciente = new EntitySet<tPaciente>(new Action<tPaciente>(this.attach_tPaciente), new Action<tPaciente>(this.detach_tPaciente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tProvincia_tPaciente", Storage="_tPaciente", ThisKey="Codigo", OtherKey="Provincia")]
		public EntitySet<tPaciente> tPaciente
		{
			get
			{
				return this._tPaciente;
			}
			set
			{
				this._tPaciente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tPaciente(tPaciente entity)
		{
			this.SendPropertyChanging();
			entity.tProvincia = this;
		}
		
		private void detach_tPaciente(tPaciente entity)
		{
			this.SendPropertyChanging();
			entity.tProvincia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tPruebas")]
	public partial class tPruebas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NIF;
		
		private System.DateTime _fecha_hora;
		
		private System.Nullable<float> _valor_glucosa;
		
		private EntityRef<tPaciente> _tPaciente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNIFChanging(string value);
    partial void OnNIFChanged();
    partial void Onfecha_horaChanging(System.DateTime value);
    partial void Onfecha_horaChanged();
    partial void Onvalor_glucosaChanging(System.Nullable<float> value);
    partial void Onvalor_glucosaChanged();
    #endregion
		
		public tPruebas()
		{
			this._tPaciente = default(EntityRef<tPaciente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIF", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NIF
		{
			get
			{
				return this._NIF;
			}
			set
			{
				if ((this._NIF != value))
				{
					if (this._tPaciente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNIFChanging(value);
					this.SendPropertyChanging();
					this._NIF = value;
					this.SendPropertyChanged("NIF");
					this.OnNIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_hora", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_hora
		{
			get
			{
				return this._fecha_hora;
			}
			set
			{
				if ((this._fecha_hora != value))
				{
					this.Onfecha_horaChanging(value);
					this.SendPropertyChanging();
					this._fecha_hora = value;
					this.SendPropertyChanged("fecha_hora");
					this.Onfecha_horaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_glucosa", DbType="Real")]
		public System.Nullable<float> valor_glucosa
		{
			get
			{
				return this._valor_glucosa;
			}
			set
			{
				if ((this._valor_glucosa != value))
				{
					this.Onvalor_glucosaChanging(value);
					this.SendPropertyChanging();
					this._valor_glucosa = value;
					this.SendPropertyChanged("valor_glucosa");
					this.Onvalor_glucosaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tPaciente_tPruebas", Storage="_tPaciente", ThisKey="NIF", OtherKey="NIF", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tPaciente tPaciente
		{
			get
			{
				return this._tPaciente.Entity;
			}
			set
			{
				tPaciente previousValue = this._tPaciente.Entity;
				if (((previousValue != value) 
							|| (this._tPaciente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tPaciente.Entity = null;
						previousValue.tPruebas.Remove(this);
					}
					this._tPaciente.Entity = value;
					if ((value != null))
					{
						value.tPruebas.Add(this);
						this._NIF = value.NIF;
					}
					else
					{
						this._NIF = default(string);
					}
					this.SendPropertyChanged("tPaciente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
